version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0  
    commands:
      - echo Installing dependencies...
      - dotnet restore
  build:
    commands:
      - echo Building the application...
      - dotnet clean SeleniumTests.sln
      - dotnet build SeleniumTests.sln --configuration Release
  post_build:
    commands:
      - echo Running tests...
      - dotnet test SeleniumTests.sln --configuration Release --verbosity detailed --logger "junit;LogFilePath=TestResults/TestResults.xml"
artifacts:
  files:
    - out/**/*
    - TestResults/TestResults.xml
  discard-paths: no

