version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0  
    commands:
      - echo Cleaning up old builds...
      - rm -rf bin/ out/ TestResults/ obj/
      - echo Installing dependencies...
      - dotnet restore
  build:
    commands:
      - echo Building the application...
      - dotnet clean SeleniumTests.sln
      - dotnet build SeleniumTests.sln --configuration Release
  post_build:
    commands:
      - echo Running tests...
      - dotnet test SeleniumTests.sln --configuration Release --verbosity detailed --logger "junit;LogFilePath=TestResults/TestResults.xml"
      - echo ? Packaging application...
      - echo ? dotnet publish -c Release -o out
artifacts:
  files:
    - out/**/*
    - TestResults/TestResults.xml
  discard-paths: no

