version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd TestProject1
      - dotnet restore
  build:
    commands:
      - echo Building the application...
      - dotnet clean 
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Running tests... disabled AWS testing due to concurrent use of saucelabs with GitHub Actions
