version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - cd TestProject1
      - dotnet restore
  build:
    commands:
      - echo Building the application...
      - dotnet clean 
      - dotnet build --configuration Release
  post_build:
    commands:
      - echo Running tests...
      - dotnet test --configuration Release
artifacts:
  files:
    - out/**/*
    - TestResults/TestResults.xml
  discard-paths: no

