name: Automated Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: goto sln dir
        run: cd ./TestProject1

      - name: Install dependencies
        run: dotnet restore
        working-directory: TestProject1

      - name: Build
        run: dotnet build --configuration Release
        working-directory: TestProject1

      - name: Run tests
        run: dotnet test --configuration Release --logger "junit;LogFilePath=TestResults\TestResults.xml"
        working-directory: TestProject1
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
